In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [64]:
dataset = pd.read_csv('klasifikasi_makhlukhidup.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [65]:
print(x)

[['human' 'warm' 'yes' 'no' 'no']
 ['python' 'cold' 'no' 'no' 'no']
 ['salmon' 'cold' 'no' 'no' 'yes']
 ['whale' 'warm' 'yes' 'no' 'yes']
 ['frog' 'cold' 'no' 'no' 'sometimes']
 ['komodo' 'cold' 'no' 'no' 'no']
 ['bat' 'warm' 'yes' 'yes' 'no']
 ['pigeon' 'warm' 'no' 'yes' 'no']
 ['cat' 'warm' 'yes' 'no' 'no']
 ['leopard shark' 'cold' 'yes' 'no' 'yes']
 ['turtle' 'cold' 'yes' 'no' 'sometimes']
 ['penguin' 'warm' 'no' 'no' 'sometimes']
 ['porcupine' 'warm' 'yes' 'no' 'no']
 ['eel' 'cold' 'no' 'no' 'yes']
 ['salamander' 'cold' 'no' 'no' 'sometimes']
 ['gila monster' 'cold' 'no' 'no' 'no']
 ['platypus' 'warm' 'no' 'no' 'no']
 ['owl' 'warm' 'no' 'yes' 'no']
 ['dolphin' 'warm' 'yes' 'no' 'yes']
 ['eagle' 'warm' 'no' 'yes' 'no']]


In [66]:
print(y)

['mamals' 'reptiles' 'fishes' 'mamals' 'amphibians' 'reptiles' 'mamals'
 'birds' 'mamals' 'fishes' 'reptiles' 'birds' 'mamals' 'fishes'
 'amphibians' 'reptiles' 'mamals' 'birds' 'mamals' 'birds']


In [67]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [68]:
print(y)

[3 4 2 3 0 4 3 1 3 2 4 1 3 2 0 4 3 1 3 1]


In [69]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [70]:
print(x_train)

[['salmon' 'cold' 'no' 'no' 'yes']
 ['salamander' 'cold' 'no' 'no' 'sometimes']
 ['frog' 'cold' 'no' 'no' 'sometimes']
 ['owl' 'warm' 'no' 'yes' 'no']
 ['pigeon' 'warm' 'no' 'yes' 'no']
 ['python' 'cold' 'no' 'no' 'no']
 ['eel' 'cold' 'no' 'no' 'yes']
 ['human' 'warm' 'yes' 'no' 'no']
 ['eagle' 'warm' 'no' 'yes' 'no']
 ['dolphin' 'warm' 'yes' 'no' 'yes']
 ['leopard shark' 'cold' 'yes' 'no' 'yes']
 ['gila monster' 'cold' 'no' 'no' 'no']
 ['cat' 'warm' 'yes' 'no' 'no']
 ['porcupine' 'warm' 'yes' 'no' 'no']
 ['penguin' 'warm' 'no' 'no' 'sometimes']
 ['komodo' 'cold' 'no' 'no' 'no']]


In [71]:
print(x_test)

[['whale' 'warm' 'yes' 'no' 'yes']
 ['platypus' 'warm' 'no' 'no' 'no']
 ['bat' 'warm' 'yes' 'yes' 'no']
 ['turtle' 'cold' 'yes' 'no' 'sometimes']]


In [73]:
print(y_train)

[2 0 0 1 1 4 2 3 1 3 2 4 3 3 1 4]


In [72]:
print(y_test)

[3 3 3 4]
